### ISSUE TITLE
Toolbar icon paths need updating

### ISSUE THREAD

**Issue by KSAMissionCtrl** [JPLRepo/KSPPersistentTrails#1]
using the Toolbar mod instead of the App Launcher has it looking for the icons as if the Persistent Trails folder was still under /GameData rather than in the RepoSoft folder

**Comment by JPLRepo** [comment]
ah ok. Will look to fix. Thanks.

**Comment by JPLRepo** [comment]
This was fixed way back in KSP 1.5.
Closing.
